apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: prometheus-example-app
    prometheus: app-prometheus
  name: prometheus-example-app
  namespace: application-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
  endpoints:
  - interval: 30s
    port: webapp

